from binance.enums import *

INTERVALS = {
    '1m': KLINE_INTERVAL_1MINUTE,
    '3m': KLINE_INTERVAL_3MINUTE,
    '5m': KLINE_INTERVAL_5MINUTE,
    '15m': KLINE_INTERVAL_15MINUTE,
    '30m': KLINE_INTERVAL_30MINUTE,
    '1h': KLINE_INTERVAL_1HOUR,
    '2h': KLINE_INTERVAL_2HOUR,
    '4h': KLINE_INTERVAL_4HOUR,
    '12h': KLINE_INTERVAL_12HOUR,
    '1d': KLINE_INTERVAL_1DAY,
    '1w': KLINE_INTERVAL_1WEEK
}
